
CREATE DATABASE e2 CHARACTER SET utf8 COLLATE utf8_general_ci;

CREATE USER 'e2'@'localhost' IDENTIFIED BY 'e2';
GRANT ALL PRIVILEGES ON *.* TO 'e2'@'localhost' WITH GRANT OPTION;
CREATE USER 'e2'@'%' IDENTIFIED BY 'e2';
GRANT ALL PRIVILEGES ON *.* TO 'e2'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;


